version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: rsu_project
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./rsu_project.sql:/docker-entrypoint-initdb.d/rsu_project.sql
